apiVersion: v1
kind: Pod
metadata:
  name: httpmirror
spec:
  containers:
  - name: cherokee
    image: localhost/cherokee:latest
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
       allowPrivilegeEscalation: false
       capabilities:
          drop:
             - CAP_MKNOD
             - CAP_NET_RAW
             - CAP_AUDIT_WRITE
       privileged: false
       readOnlyRootFilesystem: true
    tty: false
    volumeMounts:
      - mountPath: /var/www
        name: host-shared-tmp-www
  volumes:
  - hostPath:
      path: /tmp/www
      type: Directory
    name: host-shared-tmp-www
  dnsConfig: {}
  restartPolicy: Always
status: {}
